# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f8cc6b1a7358dff40bc34f4409d4b48ea65078e9122e3239f99799eb6e784c4a67e621f3c69d79cfefcda2dc0c5b2c8d7a9d7f627034e76e634f726fed942e

test:
  secret_key_base: a3806ab84d2c6fc2421963f52a36c07dc6205773e29ff61f2c55f86bbd8b9ecd0e38afa89b55c1e59cd7962ca296ec7e7d7dd8a5cd8cd8e54fb06ddd80cb3fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
